# Generated by Django 5.1.2 on 2024-10-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_time_generatordata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
