# Generated by Django 5.1.2 on 2024-10-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
